// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATf7BHIeNbeNsc5XZJEs2ekDS97Ls1oV4',
    appId: '1:516163058190:web:a6e77dcdcc1018515d9a5f',
    messagingSenderId: '516163058190',
    projectId: 'strm-dc8d5',
    authDomain: 'strm-dc8d5.firebaseapp.com',
    storageBucket: 'strm-dc8d5.firebasestorage.app',
    measurementId: 'G-EQ8DY2VEW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XlXyiWu03N89usF8ISAQBXAHJS7At_Y',
    appId: '1:516163058190:android:6109565d3471bb025d9a5f',
    messagingSenderId: '516163058190',
    projectId: 'strm-dc8d5',
    storageBucket: 'strm-dc8d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPKpuWt1G32USnlkmgmuS_oLInF7cjDA',
    appId: '1:516163058190:ios:0ec873ae3018d6d95d9a5f',
    messagingSenderId: '516163058190',
    projectId: 'strm-dc8d5',
    storageBucket: 'strm-dc8d5.firebasestorage.app',
    iosBundleId: 'com.example.strm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPKpuWt1G32USnlkmgmuS_oLInF7cjDA',
    appId: '1:516163058190:ios:0ec873ae3018d6d95d9a5f',
    messagingSenderId: '516163058190',
    projectId: 'strm-dc8d5',
    storageBucket: 'strm-dc8d5.firebasestorage.app',
    iosBundleId: 'com.example.strm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATf7BHIeNbeNsc5XZJEs2ekDS97Ls1oV4',
    appId: '1:516163058190:web:a719a753f7b931155d9a5f',
    messagingSenderId: '516163058190',
    projectId: 'strm-dc8d5',
    authDomain: 'strm-dc8d5.firebaseapp.com',
    storageBucket: 'strm-dc8d5.firebasestorage.app',
    measurementId: 'G-RY4PQQ09LT',
  );
}
